### PR TITLE
BLDKCMF-8 Compliance Issues in Lightning-SDK

### PR DESCRIPTION
**Pull request by Sukanya673**
BLDKCMF-8 Compliance Issues in Lightning-SDK

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Sukanya,
- What about headers on scripts/build.js, release.js, serve.js and upload-app-metrological.js?
- As per my email yesterday, please will you use the new form of NOTICE here too (and in -CLI when you get there).
- While you are working on NOTICE, please fix my typo in the spelling of license in the last entry.
Thank you.

**Comment by mhughesacn** [comment]
Hi Sukanya,
- What about headers on scripts/build.js, release.js, serve.js and upload-app-metrological.js?
- As per my email yesterday, please will you use the new form of NOTICE here too (and in -CLI when you get there).
- While you are working on NOTICE, please fix my typo in the spelling of license in the last entry.
Thank you.

**Comment by mhughesacn** [comment]
Hi Sukanya, Is there a reason that docs/index.html doesn't have a header (given that you added one on support/index.html)?

**Comment by Sukanya673** [comment]
> Hi Sukanya, Is there a reason that docs/index.html doesn't have a header (given that you added one on support/index.html)?

Hi @mhughesacn  docs/index.html present in 3rd row of dependency column, So that i didn't add the header information. Kindly share your suggestion to add.

**Comment by mhughesacn** [comment]
Hi @Sukanya673  Please give it a header for consistency.

**Comment by Sukanya673** [comment]
Hi @mhughesacn  Thanks for your comments. Review comments addressed. Kindly review on re work.

**Comment by mhughesacn** [comment]
Hi @Sukanya673 Looks good to me, thank you.

**Comment by pradeeptakdas** [comment]
Hi @woutermeek , Please merge this change if you are Happy, Thanks!

**Pull request merged**
